// * 必须传递用户名和密码
const USERNAME_OR_PASSWORD_IS_REQUIRED = 'USERNAME_OR_PASSWORD_IS_REQUIRED';
// * 注册时用户名已经被占用
const USERNAME_IS_ALREADY_EXISTS = 'USERNAME_IS_ALREADY_EXISTS';
// * 登录时，数据中没有此用户
const USERNAME_IS_NOT_EXIST = 'USERNAME_IS_NOT_EXIST';
// * 登录时， 密码不正确
const PASSWORD_MISTAKE = 'PASSWORD_MISTAKE';
// * 访问某些资源，检查权限
const UNAUTHENTICATED_USER = 'UNAUTHENTICATED_USER';

module.exports = {
  USERNAME_OR_PASSWORD_IS_REQUIRED,
  USERNAME_IS_ALREADY_EXISTS,
  USERNAME_IS_NOT_EXIST,
  PASSWORD_MISTAKE,
  UNAUTHENTICATED_USER
};
